---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kafkamirrormakers.kafka.strimzi.io
  labels:
    app: '{{ template "strimzi.name" . }}'
    chart: '{{ template "strimzi.chart" . }}'
    component: kafkamirrormakers.kafka.strimzi.io-crd
    release: '{{ .Release.Name }}'
    heritage: '{{ .Release.Service }}'
spec:
  group: kafka.strimzi.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: KafkaMirrorMaker
    listKind: KafkaMirrorMakerList
    singular: kafkamirrormaker
    plural: kafkamirrormakers
    shortNames:
    - mm
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            config:
              type: object
            blacklist:
              type: string
            destination:
              type: string
            destinationAuthentication:
              type: object
              properties:
                certificateAndKey:
                  type: object
                  properties:
                    certificate:
                      type: string
                    key:
                      type: string
                    secretName:
                      type: string
                  required:
                  - certificate
                  - key
                  - secretName
                passwordSecret:
                  type: object
                  properties:
                    password:
                      type: string
                    secretName:
                      type: string
                  required:
                  - password
                  - secretName
                type:
                  type: string
                username:
                  type: string
            destinationTls:
              type: object
              properties:
                trustedCertificates:
                  type: array
                  items:
                    type: object
                    properties:
                      certificate:
                        type: string
                      secretName:
                        type: string
                    required:
                    - certificate
                    - secretName
              required:
              - trustedCertificates
            source:
              type: string
            sourceAuthentication:
              type: object
              properties:
                certificateAndKey:
                  type: object
                  properties:
                    certificate:
                      type: string
                    key:
                      type: string
                    secretName:
                      type: string
                  required:
                  - certificate
                  - key
                  - secretName
                passwordSecret:
                  type: object
                  properties:
                    password:
                      type: string
                    secretName:
                      type: string
                  required:
                  - password
                  - secretName
                type:
                  type: string
                username:
                  type: string
            sourceTls:
              type: object
              properties:
                trustedCertificates:
                  type: array
                  items:
                    type: object
                    properties:
                      certificate:
                        type: string
                      secretName:
                        type: string
                    required:
                    - certificate
                    - secretName
              required:
              - trustedCertificates
            whitelist:
              type: string
